### ISSUE TITLE
Do something about "magic numbers" in CSS examples

### ISSUE THREAD

**Issue by bertfrees** [daisy/ebraille#244]
See for example the [Simple box with blank lines](https://daisy.github.io/ebraille/best-practices/styling/#example-simple-box-with-blank-lines) example:

```css
.box {
   border-style: solid;
   border-width: .45rem 0;
   margin: 1.22rem 0 1.55rem 0;
   padding: .33rem 0 0 0;
}
```

Either these numbers need an explanation (how to obtain the numbers?), or we need to recommend another approach that doesn't need the numbers (e.g. we could further develop the "[border image](https://daisy.github.io/ebraille/best-practices/styling/#example-border-image)" approach).
